#EXPERIMENT 9
#STUDY OF PANDAS LIBRARY
# DARSH JAIN
#PRN: 25070123037
# ENTC BATCH A2

In [ ]:
import pandas as pd
s= pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
#Create Dataframe
data={
    "Name":["A","B","C"],
    "Marks":[85,90,78]
}
df= pd.DataFrame(data)
print(df)

  Name  Marks
0    A     85
1    B     90
2    C     78

In [ ]:
#Find the structure of the Dataframe
df.shape

(3, 2)

In [ ]:
df.ndim

2

In [ ]:
df.size

6

In [ ]:
#Display Column Names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [ ]:
#Check Data types of each column
df.dtypes

Name     object
Marks     int64
dtype: object

In [ ]:
#Access individuals columns
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [ ]:
(df['Marks'])

0    85
1    90
2    78
Name: Marks, dtype: int64

In [ ]:
#Access Specific Row
df.loc[1]

Name      B
Marks    90
Name: 1, dtype: object

In [ ]:
#Add a new column
df["Grade"]= ["First Class","Distinction","Second Class"]
df

  Name  Marks         Grade
0    A     85   First Class
1    B     90   Distinction
2    C     78  Second Class

In [ ]:
#Update data in dataframe
#Change marks of students A to 88
df.loc[0,"Marks"]=88
df

  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    C     78  Second Class

In [ ]:
#Delete a colum
df.drop("Grade",axis=1, inplace= True)
df

  Name  Marks
0    A     88
1    B     90
2    C     78

In [ ]:
#Perform Basic Stastistical Analysis
mean1=df["Marks"].mean()
mean1

np.float64(85.33333333333333)

In [ ]:
# minimum
min1=df["Marks"].min()
min1

78

In [ ]:
#maximum
max1=df["Marks"].max()
max1

90

In [ ]:
#Apply Condition (Filtering)
#Display students scoring marks more than 80.
df[df["Marks"]>80]

  Name  Marks
0    A     88
1    B     90